package xyz.vsl.mybatis.generator.pluginsplus;

import java.util.List;
import java.util.ListIterator;
import java.util.StringTokenizer;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.*;
import org.mybatis.generator.api.dom.xml.Element;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.internal.util.StringUtility;

import static org.mybatis.generator.api.dom.java.JavaVisibility.PRIVATE;
import static org.mybatis.generator.api.dom.java.JavaVisibility.PUBLIC;
import static xyz.vsl.mybatis.generator.pluginsplus.MBGenerator.*;
import static xyz.vsl.mybatis.generator.pluginsplus.MBGenerator.FQJT.*;

/**
 * <p>Adds new methods to Example class providing the ability to join another tables</p>
 * <ul>
 *     <li>{@code addFromClause(String joinExpression)}</li>
 *     <li>{@code addFromClause(String formatString, Object arg0, Object ... args1n)}</li>
 * </ul>
 * <p>The name of the method can be configured by setting {@code methodName} plugin's property. Default value is {@code addFromClause}</p>
 * <p>Example:<br/>
 * <tt>new FooExample().addFromClause("join foo_type ft on ft.id=foo.type_id and ft.code='bar'");</tt><br/>
 * or, using {@link xyz.vsl.mybatis.generator.pluginsplus.AnyCriteriaPlugin}:<br/>
 * <tt>new FooExample().addFromClause("join foo_type ft on ft.id=foo.type_id").createCriteria().andEqualTo("ft.code", "bar");</tt><br/>
 * or<br/>
 * <tt>new FooExample().addFromClause("join foo_type ft on ft.id=%s.type_id", FooExample.ALIAS).createCriteria().andEqualTo("ft.code", "bar");</tt><br/>
 * where {@code FooExample.ALIAS} is auto-generated field. This field is initialized to contain the table alias (&lt;table&nbsp;...&nbsp;alias="..."&gt;)
 * or table name if alias is not specified.
 * </p>
 * <p></p>
 * <p>Supported Java Client generators:<br/>
 * <b>ANNOTATEDMAPPER</b>: not supported<br/>
 * <b>MIXEDMAPPER</b>: supported<br/>
 * <b>XMLMAPPER</b>: supported<br/>
 * </p>
 * @author Vladimir Lokhov
 */
public class JoinPlugin extends PluginAdapter {
    private String methodName;
    private String tableConstName;
    private String aliasConstName;
    private boolean generateExampleConst;
    private boolean generateModelConst;

    public boolean validate(List<String> warnings) {
        methodName = Objects.nvl(Str.trim(properties.getProperty("methodName")), "addFromClause");
        tableConstName = Objects.nvl(Str.trim(properties.getProperty("tableConstName")), "TABLE");
        aliasConstName = Objects.nvl(Str.trim(properties.getProperty("aliasConstName")), "ALIAS");
        generateExampleConst = Bool.bool(Str.trim(properties.getProperty("generateExampleConst")), true);
        generateModelConst = Bool.bool(Str.trim(properties.getProperty("generateModelConst")), false);
        return true;
    }

    @Override
    public boolean modelBaseRecordClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if (generateModelConst) addTableNameConstant(topLevelClass, introspectedTable);
        return true;
    }

    @Override
    public boolean modelPrimaryKeyClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if (generateModelConst) addTableNameConstant(topLevelClass, introspectedTable);
        return true;
    }

    @Override
    public boolean modelRecordWithBLOBsClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if (generateModelConst) addTableNameConstant(topLevelClass, introspectedTable);
        return true;
    }

    @Override
    public boolean modelExampleClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if (generateExampleConst) addTableNameConstant(topLevelClass, introspectedTable);
        addFromField(topLevelClass, introspectedTable);
        fixCriteriaColumns(topLevelClass, introspectedTable);

        for (Method m : topLevelClass.getMethods()) {
            if (!"clear".equals(m.getName())) continue;
            m.getBodyLines().add(0, "from = null;");
            break;
        }
        return true;
    }

     private void addTableNameConstant(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
         String alias = introspectedTable.getFullyQualifiedTable().getAlias();
         String table = MBGenerator.tableName(introspectedTable);
         if (!StringUtility.stringHasValue(alias))
             alias = table;
         String constName = Objects.nvl(Str.trim(introspectedTable.getTableConfigurationProperty("tableConstName")), tableConstName);
         topLevelClass.addField(field(PUBLIC, FINAL, STATIC, STRING, constName, _("`"+table+"`")).javadoc("This field was generated by JoinPlugin", "Name of the database table represented by this class"));
         constName = Objects.nvl(Str.trim(introspectedTable.getTableConfigurationProperty("aliasConstName")), aliasConstName);
         topLevelClass.addField(field(PUBLIC, FINAL, STATIC, STRING, constName, _("`"+alias+"`")).javadoc("This field was generated by JoinPlugin", "SQL query alias of the database table represented by this class"));
    }

    private boolean addJoinXMLs(final XmlElement element, final IntrospectedTable introspectedTable) {
        return traverse(element, new FindElements() {
            private int count = 0;
            @Override
            public boolean process(XmlElement parent, Element self, int position) {
                if (count > 0)
                    return false;
                addLater(parent, position + 1, e(
                    "if", a("test", "from != null"),
                        e("foreach", a("collection", "from"), a("item", "join"), a("separator", " "),
                            "${join}"
                        )
                ));
                count++;
                return true;
            }
        }.when(TEXT_NODE.and(depth(2, 2)).and(textMatches("^(.*\\s)?from\\s.*$", true)))) > 0;
    }

    @Override
    public boolean sqlMapSelectByExampleWithoutBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return addJoinXMLs(element, introspectedTable);
    }

    @Override
    public boolean sqlMapCountByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return addJoinXMLs(element, introspectedTable);
    }

    @Override
    public boolean sqlMapSelectByExampleWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return addJoinXMLs(element, introspectedTable);
    }

    @Override
    public boolean sqlMapBaseColumnListElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return addTablePrefix(element, introspectedTable);
    }

    @Override
    public boolean sqlMapBlobColumnListElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        return addTablePrefix(element, introspectedTable);
    }

    private boolean addTablePrefix(XmlElement element, IntrospectedTable introspectedTable) {
        if (introspectedTable.getFullyQualifiedTable() != null && StringUtility.stringHasValue(introspectedTable.getFullyQualifiedTable().getAlias()))
            return true;
        final String table = MBGenerator.tableName(introspectedTable);

        traverse(element, new FindElements() {
            private boolean first = true;

            @Override
            public boolean process(XmlElement parent, Element self, int position) {
                if (!(self instanceof TextElement)) return false;
                String s = ((TextElement) self).getFormattedContent(0).trim();
                StringBuilder sb = new StringBuilder();
                if (first) first = false;
                else sb.append(',');
                for (StringTokenizer st = new StringTokenizer(s, ", ", false); st.hasMoreTokens(); ) {
                    String field = st.nextToken();
                    sb.append(table).append('.').append(field);
                    if (st.hasMoreTokens())
                        sb.append(", ");
                }

                replaceLater(parent, position, new TextElement(sb.toString()));

                return true;
            }
        }.when(TEXT_NODE.and(depth(2, 2)).and(skipComments())));

        return true;
    }

    private void addFromField(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        topLevelClass.addField(field(PRIVATE, LIST_OF_STRING, "from"));

        topLevelClass.addMethod(method(
                PUBLIC, LIST_OF_STRING, "getFrom", __(
                        "return from;"
                )));

        topLevelClass.addMethod(method(
            PUBLIC, topLevelClass.getType(), methodName, _(STRING, "join"), __(
                "if (join == null || (join = join.trim()).length() == 0) return this;",
                "if (from == null) from = new java.util.ArrayList<String>();",
                "from.add(join);",
                "return this;"
        )));

        topLevelClass.addMethod(method(
            PUBLIC, topLevelClass.getType(), methodName, _(STRING, "formatString"), _(OBJECT, "arg0"), _(OBJECT, "args1n", true), __(
                "if (formatString == null || (formatString = formatString.trim()).length() == 0) return this;",
                "if (from == null) from = new java.util.ArrayList<String>();",
                "Object[] temp = new Object[(args1n == null ? 0 : args1n.length) + 1];",
                "if (args1n != null) System.arraycopy(args1n, 0, temp, 1, args1n.length);",
                "temp[0] = arg0;",
                "String formatted = String.format(formatString, temp);",
                "from.add(formatted);",
                "return this;"
        )).javadoc(
                "@param formatString A {@link java.util.Formatter format string} for join expression",
                "@param arg0 First argument referenced by the format specifiers in the format string",
                "@param args1n Second and further arguments referenced by the format specifiers in the format string"
        ));
    }

    private void fixCriteriaColumns(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        if (introspectedTable.getFullyQualifiedTable() != null && StringUtility.stringHasValue(introspectedTable.getFullyQualifiedTable().getAlias()))
            return;

        InnerClass generatedCriteria = null;
        for (InnerClass innerClass : topLevelClass.getInnerClasses()) {
            if ("GeneratedCriteria".equals(innerClass.getType().getShortName())) {
                generatedCriteria = innerClass;
            }
        }
        if (generatedCriteria == null)
            return;

        final String table = MBGenerator.tableName(introspectedTable);
        final String ADD_CRITERION = "addCriterion(\"";

        for (Method m : generatedCriteria.getMethods()) {
            List<String> bodyLines = m.getBodyLines();
            for (ListIterator<String> it = bodyLines.listIterator(); it.hasNext(); ) {
                String line = it.next();
                if (line.trim().startsWith(ADD_CRITERION)) {
                    it.set(line.replace(ADD_CRITERION, ADD_CRITERION+table+"."));
                }
            }
        }
    }
}
